version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: daily
      time: "18:00"
      timezone: Asia/Tokyo
    open-pull-requests-limit: 10
    reviewers:
      - "king-kazu39"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
      time: "18:00"
      timezone: Asia/Tokyo
    open-pull-requests-limit: 10
    reviewers:
      - "king-kazu39"