/// 後でJSONファイルから読み込む
// ChatRoom
const List<Map<String, dynamic>> chatRoomData = [
  // グループチャットのデータ(isGroupがtrue)
  {
    "roomId": "group-001",
    "roomName": "グループA",
    "isGroup": true,
    "userId": "a",
    "lastMessage": "やっほー",
    "profileImage":
        "https://shikimori-anime.com/core_sys/images/main/home/kv3.jpg",
    "createdAt": null,
    "updatedAt": null,
    "messages": [
      {
        "messageId": "group-001-01",
        "messageFrom": "a",
        "isSender": true,
        "userName": "Aさん",
        "profileImage": null,
        "media": null,
        "message": "おはよう",
        "createdAt": "2022/12/01",
        "updateAt": "2022/12/01",
      },
      {
        "messageId": "group-001-02",
        "messageFrom": "b",
        "isSender": false,
        "userName": "Bさん",
        "profileImage": null,
        "media": null,
        "message": "こんにちは",
        "createdAt": "2022/12/02",
        "updateAt": "2022/12/02",
      },
      {
        "messageId": "group-001-03",
        "messageFrom": "c",
        "isSender": false,
        "userName": "Cさん",
        "profileImage": null,
        "media": null,
        "message": "おはよう",
        "createdAt": "2022/12/03",
        "updateAt": "2022/12/03",
      },
    ]
  },
  {
    "roomId": "group-002",
    "roomName": "グループB",
    "isGroup": true,
    "userId": "a",
    "lastMessage": "こんばんは",
    "profileImage": "https://anime-jam.com/images/mv04.jpg",
    "createdAt": null,
    "updatedAt": null,
    "messages": [
      {
        "messageId": "group-002-01",
        "messageFrom": "a",
        "isSender": true,
        "userName": "Aさん",
        "profileImage": null,
        "media": null,
        "message": "おはよう",
        "createdAt": "2022/12/01",
        "updateAt": "2022/12/01",
      },
      {
        "messageId": "group-002-02",
        "messageFrom": "b",
        "isSender": false,
        "userName": "Bさん",
        "profileImage": null,
        "media": null,
        "message": "こんにちは",
        "createdAt": "2022/12/02",
        "updateAt": "2022/12/02",
      },
      {
        "messageId": "group-002-03",
        "messageFrom": "c",
        "isSender": false,
        "userName": "Cさん",
        "profileImage": null,
        "media": null,
        "message": "こんばんは",
        "createdAt": "2022/12/03",
        "updateAt": "2022/12/03",
      },
    ]
  },
  {
    "roomId": "group-003",
    "roomName": "グループC",
    "isGroup": true,
    "userId": "a",
    "lastMessage": "こんばんは",
    "profileImage": null,
    "createdAt": null,
    "updatedAt": null,
    "messages": [
      {
        "messageId": "group-003-01",
        "messageFrom": "a",
        "isSender": true,
        "userName": "Aさん",
        "profileImage": null,
        "media": null,
        "message": "おはよう",
        "createdAt": "2022/12/01",
        "updateAt": "2022/12/01",
      },
      {
        "messageId": "group-003-02",
        "messageFrom": "b",
        "isSender": false,
        "userName": "Bさん",
        "profileImage": null,
        "media": null,
        "message": "こんにちは",
        "createdAt": "2022/12/02",
        "updateAt": "2022/12/02",
      },
      {
        "messageId": "group-003-03",
        "messageFrom": "c",
        "isSender": false,
        "userName": "Cさん",
        "profileImage": null,
        "media": null,
        "message": "こんばんは",
        "createdAt": "2022/12/03",
        "updateAt": "2022/12/03",
      },
    ]
  },

  // ここから1 on 1チャットのデータ
  {
    "roomId": "1on1-001",
    "roomName": "もたけん",
    "isGroup": false,
    "userId": "aaaaa",
    "lastMessage": "おはよう",
    "profileImage": null,
    "createdAt": null,
    "updatedAt": null,
    "messages": [
      {
        "messageId": "1on1-001-01",
        "messageFrom": "motakenID",
        "isSender": false,
        "userName": "もたけん",
        "profileImage": null,
        "media": null,
        "message": "おはよう",
        "createdAt": "2022/12/01",
        "updateAt": "2022/12/01",
      },
      {
        "messageId": "1on1-001-02",
        "messageFrom": "motakenID",
        "isSender": false,
        "userName": "もたけん",
        "profileImage": null,
        "media": null,
        "message": "こんにちは",
        "createdAt": "2022/12/02",
        "updateAt": "2022/12/02",
      },
      {
        "messageId": "1on1-001-03",
        "messageFrom": "a",
        "isSender": true,
        "userName": "Aさん",
        "profileImage": null,
        "media": null,
        "message": "こんばんは",
        "createdAt": "2022/12/03",
        "updateAt": "2022/12/03",
      },
    ]
  },
  {
    "roomId": "1on1-002",
    "roomName": "kazuya nakazato",
    "isGroup": false,
    "userId": "aaaaa",
    "lastMessage": "おはよう",
    "profileImage": null,
    "createdAt": null,
    "updatedAt": null,
    "messages": [
      {
        "messageId": "1on1-002-01",
        "messageFrom": "kazuyaId",
        "isSender": false,
        "userName": "kazuya nakazato",
        "profileImage": null,
        "media": null,
        "message": "おはよう",
        "createdAt": "2022/12/01",
        "updateAt": "2022/12/01",
      },
      {
        "messageId": "1on1-002-02",
        "messageFrom": "Aさん",
        "isSender": true,
        "userName": "kazuya nakazato",
        "profileImage": null,
        "media": null,
        "message": "こんにちは",
        "createdAt": "2022/12/02",
        "updateAt": "2022/12/02",
      },
      {
        "messageId": "1on1-002-03",
        "messageFrom": "kazuyaId",
        "isSender": false,
        "userName": "kazuya nakazato",
        "profileImage": null,
        "media": null,
        "message": "こんばんは",
        "createdAt": "2022/12/03",
        "updateAt": "2022/12/03",
      },
    ]
  },
  {
    "roomId": "1on1-003",
    "roomName": "ニッシー",
    "isGroup": false,
    "userId": "aaaaa",
    "lastMessage": "おはよう",
    "profileImage": null,
    "createdAt": null,
    "updatedAt": null,
    "messages": [
      {
        "messageId": "1on1-003-01",
        "messageFrom": "a",
        "isSender": true,
        "userName": "Aさん",
        "profileImage": null,
        "media": null,
        "message": "おはよう",
        "createdAt": "2022/12/01",
        "updateAt": "2022/12/01",
      },
      {
        "messageId": "1on1-003-02",
        "messageFrom": "nisshyId",
        "isSender": false,
        "userName": "ニッシー",
        "profileImage": null,
        "media": null,
        "message": "こんにちは",
        "createdAt": "2022/12/02",
        "updateAt": "2022/12/02",
      },
      {
        "messageId": "1on1-003-03",
        "messageFrom": "nisshyId",
        "isSender": false,
        "userName": "ニッシー",
        "profileImage": null,
        "media": null,
        "message": "こんばんは",
        "createdAt": "2022/12/03",
        "updateAt": "2022/12/03",
      },
    ]
  },
];
