name: favoritism_communication
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter_form_builder: ^8.0.0
  form_builder_validators: ^8.6.1
  pull_to_refresh: 2.0.0
  get_storage: ^2.1.1
  webview_flutter: ^4.2.1
  flutter_link_previewer: 3.2.0
  flutter_chat_bubble: ^2.0.2
  firebase_core: ^2.13.0
  firebase: 9.0.3
  firebase_auth: ^4.8.0
  flutter_easyloading: 3.0.5
  flutter_native_splash: 2.2.14
  flutter_launcher_icons: ^0.11.0
  cloud_firestore: ^4.7.1
  firebase_storage: ^11.2.1
  cloud_functions: ^4.3.1
  flutter_localizations: 
    sdk: flutter
  flutter: 
    sdk: flutter
  badges: ^3.0.3
  google_mobile_ads: ^2.3.0
  get_cli: ^1.8.1

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

dependency_overrides:
    intl: any

flutter: 
  uses-material-design: true

  assets:
    - assets/images/
    - assets/json/