name: favoritism_communication
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter_form_builder: ^7.8.0
  form_builder_validators: ^8.3.0
  pull_to_refresh: 2.0.0
  get_storage: ^2.1.1
  webview_flutter: 3.0.4
  flutter_link_previewer: 3.2.0
  chat_bubbles: ^1.4.0
  firebase_core: ^2.9.0
  firebase: 9.0.3
  firebase_auth: 4.1.2
  flutter_easyloading: 3.0.5
  flutter_native_splash: 2.2.14
  flutter_launcher_icons: ^0.11.0
  cloud_firestore: 4.0.5
  firebase_storage: ^11.2.1
  cloud_functions: 4.0.4
  flutter_localizations: 
    sdk: flutter
  flutter: 
    sdk: flutter
  badges: ^3.0.3
  google_mobile_ads: ^2.3.0

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/images/
    - assets/json/