name: favoritism_communication
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter_form_builder: 7.7.0

  flutter_localizations:
    sdk: flutter

  flutter: 
    sdk: flutter
  form_builder_validators: ^8.3.0

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

