import 'package:flutter/material.dart';

const colorIcon = Colors.grey;
const colorChipBorder = Color.fromARGB(132, 207, 205, 205);
const colorElevatedButtonBorder = Colors.blue;
const colorElevatedButtonFgActive = Colors.white;
const colorElevatedButtonFgDeactive = Colors.blue;
const colorElevatedButtonBgActive = Colors.blue;
const colorElevatedButtonBgDeactive = Colors.white;
const colorFooterBorder = Colors.grey;
const colorFooterBg = Colors.white;
const colorFollowButtonBorderAsUnfollowed = Colors.blueAccent;
const colorTabTextAsEnabled = Colors.white;
const colorTabBgAsEnabled = Colors.grey;
const colorTabBorderAsEnabled = Colors.grey;
const colorTabTextAsDisabled = Colors.black;
const colorTabBgAsDisabled = Colors.white;
const colorTabBorderAsDisabled = Color.fromARGB(132, 207, 205, 205);
const colorMessageBarFg = Colors.white;
const colorMessageBarBorder = Colors.grey;
const colorMessageBarInputBorder = Colors.grey;
const colorMessageBarInputBorderFocused = Colors.grey;
const colorSearchBarInputBorder = Colors.grey;
const colorSearchBarInputBorderFocused = Colors.grey;
var colorChatMemberCardBorder = Colors.grey.shade300;
const colorChatMemberCardCircleBg = Colors.grey;
const colorChatMemberCardIcon = Colors.white;
var colorUserCardBorder = Colors.grey.shade300;
const colorUserCardCircleAvatarBg = Colors.grey;
const colorUserCardCircleIcon = Colors.white;
const colorChatViewBg = Colors.pinkAccent;
const colorChatViewIcon = Colors.grey;
const colorChatViewBodyBorder = Colors.black;
const colorChatViewBodyBg = Colors.white;
const colorActionChipIcon = Colors.grey;
const colorActionChipGroupBgIfIsGroupChat = Colors.yellow;
const colorActionChipGroupBgIfIsNotGroupChat = Colors.white;
const colorActionChipGroupIcon = Colors.grey;
const colorActionChipPairChatBgIfIsGroupChat = Colors.white;
const colorActionChipPairChatBgIfIsNotGroupChat = Colors.yellow;
const colorCreateChatViewBg = Colors.pink;
const colorDashboardUnselectedItem = Colors.grey;
const colorDashboardSelectedItem = Colors.pinkAccent;
const colorHomeBg = Colors.white;
const colorHomeAppBarBg = Colors.white;
const colorHomeAppBarIconBadgeText = Colors.white;
const colorHomeAppBarIconBadgeBg = Color.fromRGBO(223, 2, 89, 1);
const colorHomeAppBarIcon = Colors.grey;
const colorHomeAppBarTitle = Color.fromRGBO(228, 190, 181, 1);
const colorHomeAppBarBorderBottom = Color.fromRGBO(230, 230, 230, 1);
const colorUserCardFollowButtonFgAsFollowed = Colors.white;
const colorUserCardFollowButtonBgAsFollowed = Colors.blueAccent;
const colorUserCardFollowButtonFgAsUnfollowed = Colors.blueAccent;
const colorUserCardFollowButtonBgAsUnfollowed = Colors.white;
const colorReturnToTopButtonFg = Colors.white;
const colorReturnToTopButtonBg = Color.fromRGBO(236, 188, 179, 1);
const colorMypageAppBarBg = Colors.pinkAccent;
const colorChatRoomAppBarBg = Colors.pink;
const colorMatchingDialogButtonTextFg = Colors.white;
const colorMatchingDialogButtonTextBg = Color(0xff0091ea);
var colorChatBubbleBg = Colors.grey.shade200;
const colorChatBubbleText = Colors.black;

// "さがす"画面
const colorSearchBg = Colors.white; // 背景色
const colorSearchAppBarBg = Colors.white; // Appbar背景色
const colorSearchAppBarTitle = Colors.grey; // タイトル文字色
const colorSearchAppBarIconFilter = Colors.grey;    // フィルターアイコン色

